spring:
  profiles:
    active: mysql
  batch:
    job:
      names: ${job.name:NONE}

#---
#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
---
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
#      password: 71405999
    url: jdbc:mysql://localhost:3306/test
  jpa:
    hibernate:
      ddl-auto: create
