spring:
  profiles:
#    local: My Mac/ enter: enter mac
    active: local
  batch:
    job:
      names: ${job.name:NONE}
#---
#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
logging:
  level:
    org:
      springframework:
        batch: INFO
---
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 71405999
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
  jpa:
    database: mysql

#  jpa:
#    hibernate:
#      ddl-auto: create
